### ISSUE TITLE
Conda compatibility with python3.8

### ISSUE THREAD

**Issue by TheMadBug** [brentp/cyvcf2#151]
Similar to #136 we've managed to run cyvcf2 in a python3.8 environment with no problems.
There appears to be a python 3.6 and 3.7 version for 0.20.0 in conda, with the 3.7 one stating this in dependencies
"python >=3.7,<3.8.0a0"
https://anaconda.org/bioconda/cyvcf2/files

Is it possible to get a python3.8 compatible conda package?
Thanks

**Comment by brentp** [comment]
It seems that as long as the file is cython'ed with python3.8, it works in 3.7 and 3.8.
I've been relying on @ccwang002 's expertise as I can no longer keep track of all these python packaging and version changes. AFAICT, it should work with 3.8 and there's no reason for the
dependency: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/cyvcf2/build.sh

Any insight @ccwang002 ?

**Comment by ccwang002** [comment]
We no longer fix the python version: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/cyvcf2/meta.yaml, so it's up to the bioconda CI to determine the python version.

I haven't been following bioconda/conda-forge lately, but I can see the [python 3.8 migration is still ongoing on conda-forge](https://conda-forge.org/status/). So likely that bioconda is still  building only python 3.6 and 3.7. Some packages have python 3.8 due to config accidents. Once the bioconda team ticks 3.8 in their CI, cyvcf2 should have the 3.8 package too.

I too would love to have the 3.8 conda package too :)

**Comment by brentp** [comment]
Thanks @ccwang002 looks like we're all ready once conda-forge is done.

**Comment by ccwang002** [comment]
Looks like Python 3.8 version of cyvcf2 is now available on bioconda. See more info about the migration at https://github.com/bioconda/bioconda-recipes/issues/24215

**Comment by ccwang002** [comment]
cyvcf2 with python 3.8 has been available on bioconda. I will close this issue but feel free to reopen if you encounter any problem.
