### ISSUE TITLE
variant.FILTER is None

### ISSUE THREAD

**Issue by moonso** [brentp/cyvcf2#51]
Hi,

when parsing vcfs with cyvcf2 there `variant.FILTER` is always `None`.
I have tried with different vcf files and the result is always the same. Is this a known bug or is there something I'm missing?
I can provide examples but are not sure if it would help...

**Comment by moonso** [comment]
Hehe sorry, just realized that `PASS` is considered as no filter..

**Comment by sjin09** [comment]
I am writing to inquire whether it would be more intuitive for the PASS filter to be designated as "PASS" instead of None. I was also surprised to find that this is not the case.

**Comment by ecapriotti** [comment]
Hi,
there is some problem with FILTER field. The program correctly reports in FILTERS the filters splitted by   semicolumn but do not find them in the header because I believe is trying to match the full string without splitting.
As a result to include the processed variant can not be written in an output file and it is skipped unless I add to the header the complete the full.

**Comment by brentp** [comment]
@ecapriotti can you share a script and small VCF to replicate what you mean?

**Comment by ecapriotti** [comment]
processed = 0
    removed_count = 0

    for variant in vcf_in:
        # Remove fields - CORRECT WAY using .get()
        for field in fields_to_remove:
            if variant.INFO.get(field) is not None:
                del variant.INFO[field]
                removed_count += 1

        print (f"Processed {variant.CHROM,variant.POS} variant", file=sys.stderr)
        vcf_out.write_record(variant)
        processed += 1

is failing here vcf_out.write_record(variant)

**Comment by ecapriotti** [comment]
Hi Brent
I am sorry for not providing all the info before.
I am sending the short script for removing an INFO filed and a small vcf for testing it.
Two varaiants in positions 113596699 and 113596705 are not retained because they have a complex FILTER field that is splitted but probably not properly matched with the single FILTERS defined in the header.
the command I am running is the following command

python clean_vcf_info.py  test.vcf -o file3.vcf -f CC_TREND_ALL --verbose

here the script [clean_vcf_info.py](http://biofold.org/tmp/clean_vcf_info.py)
here the input file: [test.vcf](http://biofold.org/tmp/test.vcf)


Thank you very much for your assistance.
Emidio

**Comment by brentp** [comment]
@ecapriotti I got a bit confused because this is about FILTER, but you seem to be removing flags from the INFO field.

If you make it easy for me to reproduce and test, then I will have a look.

**Comment by ecapriotti** [comment]
Dear Brent
I am sorry for not sending all the info before.
I have now updated my comment providing more details.
Many thanks for your assistance.
Emidio

______________________________

I am sending the short script for removing an INFO filed and a small vcf for testing it.
Two varaiants in positions 113596699 and 113596705 are not retained because they have a complex FILTER field that is splitted but probably not properly matched with the single FILTERS defined in the header.
the command I am running is the following command

python clean_vcf_info.py test.vcf -o file3.vcf -f CC_TREND_ALL --verbose

here the script clean_vcf_info.py <http://biofold.org/tmp/clean_vcf_info.py>
here the input file: test.vcf <http://biofold.org/tmp/test.vcf>
