### ISSUE TITLE
`is_indel` returns False for ALT = . record

### ISSUE THREAD

**Issue by krrome** [brentp/cyvcf2#82]
I tried the following made-up test VCF file and record.is_indel is false for the following lines:

```
##fileformat=VCFv4.0
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr22	30630220	rsXX1	T	.	.	.	.
chr22	30630220	rsXX2	.	G	.	.	.
```

**Comment by brentp** [comment]
I'm not sure those are indels. According to (my reading of) the spec, REF should always be specified so I think your 2nd entry is invalid.

For your first entry, the spec says: `If there are no alternative alleles, then the missing value should be used.` So it's valid, but, since the ALT is not indicated, we have no way of knowing if it's an indel. It could as correctly be a SNP.

**Comment by krrome** [comment]
Good point, I just went through the definition again too - seems like the "." should never appear - neither in REF nor in ALT. Must have been an invalid VCF where I encountered that, sorry. I'll close the issue.
