### ISSUE TITLE
Error with fonctions ".gt_depths" and ".gt_alt_depths" for genotypes "1/1"

### ISSUE THREAD

**Issue by YoannAnselmetti** [brentp/cyvcf2#97]
Hi,

it seems there is a problem to extract the coverage of reference and alternative allele of a genotype with cyvcf2.

With the following variant:
 3_Tms_b3v06_scaf000060	236923	.	C	A	363.27	PASS	AC=2;AF=0.2;AN=10;DP=50;ExcessHet=0.2482;FS=0;MLEAC=2;MLEAF=0.2;MQ=60;QD=30.87;SOR=0.892	GT:AD:DP:FT:GQ:PGT:PID:PL	0/0:9,0:9:f:27:.:.:0,27,317	0/0:11,0:11:PASS:33:.:.:0,33,391	1/1:0,9:9:f:27:1|1:236854_AG_A:405,27,0	0/0:9,0:9:f:24:.:.:0,24,360	0/0:12,0:12:PASS:36:.:.:0,36,431

if I want to get the coverage of reference and alternative allele of the 5 genotypes, I use the following sentences:
variant.gt_depths
variant.gt_alt_depths

And If I pint their results, I get:
print variant.gt_depths
[ 9 11  9  9 12]
print variant.gt_alt_depths
 [0 0 9 0 0]
 
Then for the 3rd genotype ("1/1"), there is coverage=9 for the reference allele. But this value should be equal to 0....
I get this error for all the genotypes "1/1"

Do you have a solution to resolve this error or is it possible for you to correct it and submit a new release of cyvcf2?
Thanks in advance for your answer.
Yoann

**Comment by brentp** [comment]
You are showing alt depths. That sample should have 9 for alt depth

**Comment by brentp** [comment]
Oh. I think I see the source of confusion. Use gt_ref_depths to get the reference counts

**Comment by YoannAnselmetti** [comment]
Thanks, If I use gt_depths it gives the depths for reference+alternative alleles. Is it?

**Comment by brentp** [comment]
yes
+ `gt_depths`: total depth
+ `gt_alt_depths`: alternate depth
+ `gt_ref_depths`: reference depth.

**Comment by snashraf** [comment]
Hi Brent,

I have a .vcf file like this

1       16693725        .       T       G       .       PASS    DP=67;MQ=60;MQ0=0;NT=ref;QSS=59;QSS_NT=56;ReadPosRankSum=0.66;SGT=TT->GT;SNVSB=0;SOMATIC;SomaticEVS=14.77;TQSS=1;TQSS_NT=1      GT:DP:FDP:SDP:SUBDP:AU:CU:GU:TU:AF      0/0:10:0:0:0:0,0:0,0:0,0:10,12:0        0/1:55:1:0:0:0,0:1,1:9,10:44,44:0.163636
 
I am trying to get depth, ref, and alt like this.

dp = variant.gt_depths
rdp = variant.gt_ref_depths
adp = variant.gt_alt_depths
but I am getting (array([-1, -1], dtype=int32), array([-1, -1], dtype=int32), array([-1, -1], dtype=int32))
This is a strelka file .  is it because of different format field ? I am attaching an example file.


[TEMP.vcf.txt](https://github.com/brentp/cyvcf2/files/6157825/TEMP.vcf.txt)

**Comment by brentp** [comment]
hi, cyvcf2 using AD to get the depths and your VCF does not have that. so you'll have to use e.g.

`variant.format('DP')` to get the depth, I'm not sure if it has the alt counts but the header of your VCF should give clue there.
